services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    network_mode: bridge

  dockergen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=test@example.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  prod-backend:
    image: ghcr.io/mugdha-adhav/splitter/backend:latest
    environment:
      - VIRTUAL_HOST=splitter.mriyam.com
      - VIRTUAL_PATH=/api/v1
      - LETSENCRYPT_HOST=splitter.mriyam.com
      - LETSENCRYPT_TEST=true
    network_mode: bridge

  dev-backend:
    image: ghcr.io/mugdha-adhav/splitter/backend:edge
    environment:
      - VIRTUAL_HOST=dev.splitter.mriyam.com
      - VIRTUAL_PATH=/api/v1
      - LETSENCRYPT_HOST=dev.splitter.mriyam.com
      - LETSENCRYPT_TEST=true
    network_mode: bridge

    prod-frontend:
    image: ghcr.io/mugdha-adhav/splitter/frontend:latest
    environment:
      - VIRTUAL_HOST=splitter.mriyam.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=splitter.mriyam.com
      - LETSENCRYPT_TEST=true
    network_mode: bridge

  dev-frontend:
    image: ghcr.io/mugdha-adhav/splitter/frontend:edge
    environment:
      - VIRTUAL_HOST=dev.splitter.mriyam.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=dev.splitter.mriyam.com
      - LETSENCRYPT_TEST=true
    network_mode: bridge

volumes:
  conf:
  html:
  certs:
  acme:
