name: Deploy code to prod

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && contains(github.head_branch,'v*.*.*')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy Prod Service
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          set -x
          ssh $SSH_USER@$SSH_HOST << EOF
            cd $DEPLOY_PATH
            docker compose pull prod
            docker compose restart prod
          EOF
